### ISSUE TITLE
RMX1971CN Issues

### ISSUE THREAD

**Issue by yuan22** [thesprintster/device_realme_RMX1971#1]
I use this device can't touch the screen for  RMX1971CN,I think it may be a kernel problem.How can I solve it? thank

**Comment by TmvJosue** [comment]
Seems to be that the Firmware of the touch screen has changed in an update, and the devs are waiting for a driver update from realme/oppo.

**Comment by yuan22** [comment]
> Seems to be that the Firmware of the touch screen has changed in an update, and the devs are waiting for a driver update from realme/oppo.

Is the message reliable?I don't know if the Realme Q is different from the realeme 5 pro.Or just the firmware or the kernel is different

**Comment by ShivamKumarJha** [comment]
> > Seems to be that the Firmware of the touch screen has changed in an update, and the devs are waiting for a driver update from realme/oppo.
> 
> Is the message reliable?I don't know if the Realme Q is different from the realeme 5 pro.Or just the firmware or the kernel is different

yeah it happens on 5 pro as well. realme gave touchscreen firmware in release. flash stock kernel zimage or lineage boot.img

**Comment by yuan22** [comment]
> please check [this](https://github.com/realme-kernel-opensource/realmeQ_realme5Pro-kernel-source/issues/1) and comment.
> realme gave old touchscreen code ;(
> 
> flash stock or lineage boot.img to fix it

Thank you, realme has been updated today.

**Comment by thesprintster** [comment]
fixed [here](https://github.com/thesprintster/kernel_realme_RMX1971/commit/095d00288918c355a38b72d5d0ceb6a17d5c4e5d)
